version: '3.8'
services:
  minecraft:
    image: 'dcjulian29/bedrock:latest'
    environment:
      - TZ=America/New_York
    ports:
      - '19132:19132/udp'
    volumes:
      - ../.docker/bedrock:/minecraft/worlds
      - ./server.properties:/minecraft/server.properties:ro
