services:
  minecraft:
    image: 'dcjulian29/minecraft:latest'
    environment:
      - PGID=1001
      - PUID=1001
    ports:
      - '25565:25565'
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "./.docker/banned-ips.json:/minecraft/banned-ips.json"
      - "./.docker/banned-players.json:/minecraft/banned-players.json"
      - "./.docker/ops.json:/minecraft/ops.json"
      - "./.docker/server.properties:/minecraft/server.properties:ro"
      - "./.docker/whitelist.json:/minecraft/whitelist.json"
      - "./.docker/vanilla/logs:/minecraft/logs"
      - "./.docker/vanilla/world:/minecraft/world"
