version: '3.8'
services:
  minecraft:
    image: 'dcjulian29/minecraft:latest'
    environment:
      - TZ=America/New_York
    ports:
      - '25565:25565'
    volumes:
      - ./server.properties:/minecraft/server.properties:ro
      - ./.docker/banned-ips.json:/minecraft/banned-ips.json
      - ./.docker/banned-players.json:/minecraft/banned-players.json
      - ./.docker/ops.json:/minecraft/ops.json
      - ./.docker/whitelist.json:/minecraft/whitelist.json
      - ./.docker/vanilla/logs:/minecraft/logs
      - ./.docker/vanilla/world:/minecraft/world
