version: '3.8'
services:
  minecraft:
    image: 'dcjulian29/minecraft:latest-paper'
    environment:
      - TZ=America/New_York
    ports:
      - '8123:8123'
      - '25565:25565'
    volumes:
      - ../.docker/paper/world:/minecraft/world
      - ../.docker/paper/nether:/minecraft/world_nether
      - ../.docker/paper/the_end:/minecraft/world_the_end
      - ../ops.json:/minecraft/ops.json
