version: '3.8'
services:
  minecraft:
    image: 'dcjulian29/minecraft:latest-spigot'
    environment:
      - TZ=America/New_York
    ports:
      - '8123:8123'
      - '25565:25565'
      - '19132:19132/udp'
    volumes:
      - ../banned-ips.json:/minecraft/banned-ips.json
      - ../banned-players.json:/minecraft/banned-players.json
      - ../ops.json:/minecraft/ops.json
      - ./server.properties:/minecraft/server.properties:ro
      - ../whitelist.json:/minecraft/whitelist.json
      - ../.docker/logs-spigot:/minecraft/logs
      - ../.docker/spigot/world:/minecraft/world
      - ../.docker/spigot/nether:/minecraft/world_nether
      - ../.docker/spigot/the_end:/minecraft/world_the_end
      - ../.docker/spigot/julian:/minecraft/julian
      - ../.docker/spigot/dynmap:/minecraft/plugins/dynmap/web/tiles
      - ./bukkit.yml:/minecraft/bukkit.yml
      - ./spigot.yml:/minecraft/spigot.yml
      - ./worlds.yml:/minecraft/plugins/Multiverse-Core/worlds.yml
      - ./portals.yml:/minecraft/plugins/Multiverse-Portals/portals.yml
      - ../.docker/spigot/worldedit.log:/minecraft/plugins/WorldEdit/worldedit.log
