version: '3.8'
services:
  minecraft:
    image: 'dcjulian29/minecraft:latest-spigot'
    environment:
      - TZ=America/New_York
    ports:
      - '8123:8123'
      - '25565:25565'
      - '19132:19132/udp'
    volumes:
      - ../.docker/banned-ips.json:/minecraft/banned-ips.json
      - ../.docker/banned-players.json:/minecraft/banned-players.json
      - ../.docker/ops.json:/minecraft/ops.json
      - ../.docker/whitelist.json:/minecraft/whitelist.json
      - ../.docker/spigot/bukkit.yml:/minecraft/bukkit.yml
      - ../.docker/spigot/server.properties:/minecraft/server.properties:ro
      - ../.docker/spigot/spigot.yml:/minecraft/spigot.yml
      - ../.docker/spigot/worlds.yml:/minecraft/plugins/Multiverse-Core/worlds.yml
      - ../.docker/spigot/portals.yml:/minecraft/plugins/Multiverse-Portals/portals.yml
      - ../.docker/paper/dynmap:/minecraft/plugins/dynmap/web/tiles
      - ../.docker/paper/julian:/minecraft/julian
      - ../.docker/paper/logs:/minecraft/logs
      - ../.docker/paper/nether:/minecraft/world_nether
      - ../.docker/paper/the_end:/minecraft/world_the_end
      - ../.docker/paper/world:/minecraft/world
      - ../.docker/plugins:/minecraft/plugins
