services:
  minecraft:
    image: 'dcjulian29/minecraft:latest-spigot'
    environment:
      - PGID=1001
      - PUID=1001
    ports:
      - '8123:8123'
      - '25565:25565'
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "../.docker/banned-ips.json:/minecraft/banned-ips.json"
      - "../.docker/banned-players.json:/minecraft/banned-players.json"
      - "../.docker/ops.json:/minecraft/ops.json"
      - "../.docker/server.properties:/minecraft/server.properties:ro"
      - "../.docker/whitelist.json:/minecraft/whitelist.json"
      - "../.docker/plugins:/minecraft/plugins"
      - "../.docker/spigot/logs:/minecraft/logs"
      - "../.docker/spigot/world:/minecraft/world"
      - "../.docker/spigot/nether:/minecraft/world_nether"
      - "../.docker/spigot/the_end:/minecraft/world_the_end"
      - "../.docker/bukkit.yml:/minecraft/bukkit.yml"
      - "../.docker/spigot.yml:/minecraft/spigot.yml"
