version: '3.8'
services:

  bungeecord:
    image: dcjulian29/bungeecord:latest
    ports:
      - '25565:25565'
    depends_on:
      spigot1:
        condition: service_healthy
      spigot2:
        condition: service_healthy
      spigot3:
        condition: service_healthy
    volumes:
      - ./bungeecord.yml:/minecraft/config.yml
    networks:
      - minecraft

  spigot1:
    image: dcjulian29/minecraft:latest-spigot
    volumes:
      - ../.docker/spigot1/world:/minecraft/world
      - ../.docker/spigot1/nether:/minecraft/world_nether
      - ../.docker/spigot1/the_end:/minecraft/world_the_end
      - ../.docker/ops.json:/minecraft/ops.json
      - ./server.properties:/minecraft/server.properties:ro
      - ./spigot.yml:/minecraft/spigot.yml
      - ./bukkit.yml:/minecraft/bukkit.yml
    networks:
      - minecraft

  spigot2:
    image: dcjulian29/minecraft:latest-spigot
    volumes:
      - ../.docker/spigot2/world:/minecraft/world
      - ../.docker/spigot2/nether:/minecraft/world_nether
      - ../.docker/spigot2/the_end:/minecraft/world_the_end
      - ../.docker/ops.json:/minecraft/ops.json
      - ./server.properties:/minecraft/server.properties:ro
      - ./spigot.yml:/minecraft/spigot.yml
      - ./bukkit.yml:/minecraft/bukkit.yml
    networks:
      - minecraft

  spigot3:
    image: dcjulian29/minecraft:latest-spigot
    volumes:
      - ../.docker/spigot3/world:/minecraft/world
      - ../.docker/spigot3/nether:/minecraft/world_nether
      - ../.docker/spigot3/the_end:/minecraft/world_the_end
      - ../.docker/ops.json:/minecraft/ops.json
      - ./server.properties:/minecraft/server.properties:ro
      - ./spigot.yml:/minecraft/spigot.yml
      - ./bukkit.yml:/minecraft/bukkit.yml
    networks:
      - minecraft

networks:
  minecraft:
    driver: bridge
