FROM alpine:latest

ENV TZ        UTC

RUN apk update && apk add openjdk11-jre && rm -rf /var/cache/apk/*

RUN mkdir /minecraft && cd /minecraft \
    && wget "https://ci.md-5.net/job/BungeeCord/lastSuccessfulBuild/artifact/bootstrap/target/BungeeCord.jar"

EXPOSE 25565

VOLUME [ "/minecraft/config.yml" ]

WORKDIR /minecraft

ENTRYPOINT [ "java", "-XX:+UseCGroupMemoryLimitForHeap", "-XX:+UseG1GC", "-XX:+ParallelRefProcEnabled", "-XX:MaxGCPauseMillis=200", "-XX:+UnlockExperimentalVMOptions", "-XX:+DisableExplicitGC", "-XX:+AlwaysPreTouch", "-XX:G1NewSizePercent=60", "-XX:G1MaxNewSizePercent=80", "-XX:G1HeapRegionSize=8M", "-XX:G1ReservePercent=20", "-XX:G1HeapWastePercent=5", "-XX:G1MixedGCCountTarget=4", "-XX:InitiatingHeapOccupancyPercent=15", "-XX:G1MixedGCLiveThresholdPercent=90", "-XX:G1RSetUpdatingPauseTimePercent=5", "-XX:SurvivorRatio=32", "-XX:+PerfDisableSharedMem", "-XX:MaxTenuringThreshold=1", "-Dusing.aikars.flags=https://mcflags.emc.gs", "-Daikars.new.flags=true", "-jar", "/minecraft/BungeeCord.jar" ]
