version: '3.8'
services:
  minecraft:
    image: 'dcjulian29/minecraft:latest'
    environment:
      - TZ=America/New_York
    ports:
      - '25565:25565'
    volumes:
      - ./.docker/minecraft/world:/minecraft/world
      - ./.docker/minecraft/nether:/minecraft/world_nether
      - ./.docker/minecraft/the_end:/minecraft/world_the_end
      - ./ops.json:/minecraft/ops.json
