version: '3.8'
services:
  minecraft:
    image: 'dcjulian29/minecraft:latest'
    environment:
      - TZ=America/New_York
    ports:
      - '25565:25565'
    volumes:
      - ./banned-ips.json:/minecraft/banned-ips.json
      - ./banned-players.json:/minecraft/banned-players.json
      - ./ops.json:/minecraft/ops.json
      - ./server.properties:/minecraft/server.properties:ro
      - ./whitelist.json:/minecraft/whitelist.json
      - ./.docker/logs-vanilla:/minecraft/logs
      - ./.docker/vanilla:/minecraft/world
