FROM alpine:latest

ENV TZ        UTC

RUN apk update && apk add openjdk11-jre git

RUN mkdir /minecraft && cd /minecraft \
    && wget "https://launcher.mojang.com/v1/objects/1b557e7b033b583cd9f66746b7a9ab1ec1673ced/server.jar" \
    && echo eula=true > eula.txt

RUN rm -Rf /tmp/* /var/tmp/* \
    && rm -rf /var/cache/apk/*

EXPOSE 25565

VOLUME [ "/minecraft/world" ]

WORKDIR /minecraft

ENTRYPOINT [ "java", "-XX:+UseCGroupMemoryLimitForHeap", "-XX:+UseG1GC", "-XX:+ParallelRefProcEnabled", "-XX:MaxGCPauseMillis=200", "-XX:+UnlockExperimentalVMOptions", "-XX:+DisableExplicitGC", "-XX:+AlwaysPreTouch", "-XX:G1NewSizePercent=60", "-XX:G1MaxNewSizePercent=80", "-XX:G1HeapRegionSize=8M", "-XX:G1ReservePercent=20", "-XX:G1HeapWastePercent=5", "-XX:G1MixedGCCountTarget=4", "-XX:InitiatingHeapOccupancyPercent=15", "-XX:G1MixedGCLiveThresholdPercent=90", "-XX:G1RSetUpdatingPauseTimePercent=5", "-XX:SurvivorRatio=32", "-XX:+PerfDisableSharedMem", "-XX:MaxTenuringThreshold=1", "-Dusing.aikars.flags=https://mcflags.emc.gs", "-Daikars.new.flags=true", "-jar", "/minecraft/server.jar", "nogui" ]
