FROM alpine:latest

ENV TZ        UTC

RUN apk update && apk add openjdk11-jre git

RUN mkdir /minecraft && cd /minecraft \
    && wget "https://launcher.mojang.com/v1/objects/1b557e7b033b583cd9f66746b7a9ab1ec1673ced/server.jar" \
    && echo eula=true > eula.txt

RUN rm -Rf /tmp/* /var/tmp/* \
    && rm -rf /var/cache/apk/*

EXPOSE 25565

VOLUME [ "/minecraft/world" ]

WORKDIR /minecraft

ENTRYPOINT [ "java", "-Xms1024M", "-Xmx1024M", "-jar", "/minecraft/server.jar", "nogui" ]
