name: Build Docker Image - BungeeCord

on:
  push:
    paths:
      - bungeecord/Dockerfile
      - VERSION_BUNGEECORD

  pull_request:
    paths:
      - bungeecord/Dockerfile
      - VERSION_BUNGEECORD

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Grab the version to use.
        id: v1
        run: echo "version=$(cat VERSION_BUNGEECORD)" >> $GITHUB_OUTPUT

      - name: Grab the timestamp to use.
        id: v2
        run: echo "timestamp=$(cat GITHUB_SHA:0:12)" >> $GITHUB_OUTPUT

      - name: Build the Bungeecord Docker image.
        uses: docker/build-push-action@v3
        with:
          context: bungeecord/
          build-args: |
            VERSION=${{ steps.v1.outputs.version }}
          tags: dcjulian29/bungeecord:${{ steps.v1.outputs.version }}-${{ steps.v2.outputs.timestamp }}
