name: BungeeCord

'on':
  push:
    paths:
      - bungeecord/Dockerfile
      - VERSION_BUNGEECORD

  pull_request:
    paths:
      - bungeecord/Dockerfile
      - VERSION_BUNGEECORD

jobs:
  build:
    if: ${{ ! startsWith(github.ref, 'tags/') }}
    name: Build Docker Image - BungeeCord
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Grab the version to use.
        id: v1
        run: echo "version=$(cat VERSION_BUNGEECORD)" >> $GITHUB_OUTPUT

      - name: Grab the timestamp to use.
        id: v2
        run: echo "timestamp=$(cat GITHUB_SHA:0:12)" >> $GITHUB_OUTPUT

      - name: Build the Bungeecord Docker image.
        uses: docker/build-push-action@v3
        with:
          context: bungeecord/
          build-args: |
            VERSION=${{ steps.v1.outputs.version }}
          tags: dcjulian29/bungeecord:${{ steps.v1.outputs.version }}-${{ steps.v2.outputs.timestamp }}

  release:
    if: ${{ startsWith(github.ref, 'tags/c') }}
    name: Release Docker Image - BungeeCord
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to DockerHub.
        uses: docker/login-action@v2
        with:
          username: dcjulian29
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Grab the version to use.
        id: v1
        run: echo "version=$(cat VERSION_BUNGEECORD)" >> $GITHUB_OUTPUT

      - name: Build the BungeeCord Docker image.
        uses: docker/build-push-action@v3
        with:
          context: bungeecord
          build-args: |
            VERSION=${{ steps.v1.outputs.version }}
          push: true
          tags: |
            dcjulian29/bungeecord:${{ steps.v1.outputs.version }}
            dcjulian29/bungeecord:latest
