name: Minecraft

'on':
  push:
    paths:
      - Dockerfile
      - paper/Dockerfile
      - HASH
      - VERSION
      - VERSION_PAPER

  pull_request:
    paths:
      - Dockerfile
      - paper/Dockerfile
      - HASH
      - VERSION
      - VERSION_PAPER

jobs:
  build:
    if: ${{ ! startsWith(github.ref, 'refs/tags/') }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Grab the version to use.
        id: v1
        run: echo "version=$(cat ${{ github.workspace }}/VERSION)" >> $GITHUB_OUTPUT

      - name: Grab the timestamp to use.
        id: v2
        run: echo "timestamp=$(cat GITHUB_SHA:0:12)" >> $GITHUB_OUTPUT

      - name: Grab the paper version to use.
        id: v3
        run: echo "version=$(cat ${{ github.workspace }}/VERSION_PAPER)" >> $GITHUB_OUTPUT

      - name: Grab the hash to use.
        id: v4
        run: echo "hash=$(cat ${{ github.workspace }}/HASH)" >> $GITHUB_OUTPUT

      - name: Build the Vanilla Docker image.
        uses: docker/build-push-action@v6
        with:
          build-args: |
            HASH=${{ steps.v4.outputs.hash }}
          context: .
          push: false
          tags: |
            dcjulian29/minecraft:${{ steps.v1.outputs.version }}-${{ steps.v2.outputs.timestamp }}

      - name: Build the Paper Docker image.
        uses: docker/build-push-action@v6
        with:
          build-args: |
            VERSION=${{ steps.v1.outputs.version }}
            BUILD=${{ steps.v3.outputs.version }}
          context: paper/
          push: false
          tags: |
            dcjulian29/minecraft:${{ steps.v1.outputs.version }}-${{ steps.v2.outputs.timestamp }}-paper

  release_minecraft:
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Login to DockerHub.
        uses: docker/login-action@v3
        with:
          username: dcjulian29
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Grab the version to use.
        id: v1
        run: echo "version=$(cat VERSION)" >> $GITHUB_OUTPUT

      - name: Grab the hash to use.
        id: v2
        run: echo "hash=$(cat HASH)" >> $GITHUB_OUTPUT

      - name: Release the Vanilla Docker image.
        uses: docker/build-push-action@v6
        with:
          build-args: |
            HASH=${{ steps.v2.outputs.hash }}
          context: .
          push: true
          tags: |
            dcjulian29/minecraft:${{ steps.v1.outputs.version }}
            dcjulian29/minecraft:latest

  release_paper:
    needs: [release_minecraft]
    name: Release Docker Image - Minecraft Paper
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to DockerHub.
        uses: docker/login-action@v3
        with:
          username: dcjulian29
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Grab the version to use.
        id: v1
        run: echo "version=$(cat VERSION)" >> $GITHUB_OUTPUT

      - name: Grab the paper version to use.
        id: v3
        run: echo "version=$(cat VERSION_PAPER)" >> $GITHUB_OUTPUT

      - name: Release the Paper Docker image.
        uses: docker/build-push-action@v6
        with:
          build-args: |
            VERSION=${{ steps.v1.outputs.version }}
            BUILD=${{ steps.v3.outputs.version }}
          context: paper
          push: true
          tags: |
            dcjulian29/minecraft:${{ steps.v1.outputs.version }}-paper
            dcjulian29/minecraft:latest-paper
