name: Release Image - Minecraft

on:
  push:
    branches:
      - main
    tags:
      - '*'
      - '!b*'
      - '!c*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Login to DockerHub.
        uses: docker/login-action@v2
        with:
          username: dcjulian29
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Grab the version to use.
        id: vars
        run: echo "::set-output name=version::$(echo ${GITHUB_REF:10})"

      - name: Build the Vanilla Docker image.
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: |
            dcjulian29/minecraft:${{ steps.vars.outputs.version }}
            dcjulian29/minecraft:latest

      - name: Build the Paper Docker image.
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: |
            dcjulian29/minecraft:${{ steps.vars.outputs.version }}-paper
            dcjulian29/minecraft:latest-paper

      - name: Build the Spigot Docker image.
        uses: docker/build-push-action@v3
        with:
          build-args: |
            VERSION=1.19
          push: true
          tags: |
             dcjulian29/minecraft:${{ steps.vars.outputs.version }}-spigot
             dcjulian29/minecraft:latest-spigot
