name: Bedrock Release

on:
  push:
    tags:
      - 'b[0-9]*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Login to DockerHub.
        uses: docker/login-action@v2
        with:
          username: dcjulian29
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Grab the version to use.
        id: vars
        run: echo "::set-output name=version::$(echo ${GITHUB_REF:11})"

      - name: Build the Bedrock Docker image.
        uses: docker/build-push-action@v3
        with:
          context: bedrock
          push: true
          tags: |
            dcjulian29/bedrock:${{ steps.vars.outputs.version }}
            dcjulian29/bedrock:latest
